// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: tokenlist/v1/tokenlsit.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTokenListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain string `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
}

func (x *GetTokenListReq) Reset() {
	*x = GetTokenListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenlist_v1_tokenlsit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenListReq) ProtoMessage() {}

func (x *GetTokenListReq) ProtoReflect() protoreflect.Message {
	mi := &file_tokenlist_v1_tokenlsit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenListReq.ProtoReflect.Descriptor instead.
func (*GetTokenListReq) Descriptor() ([]byte, []int) {
	return file_tokenlist_v1_tokenlsit_proto_rawDescGZIP(), []int{0}
}

func (x *GetTokenListReq) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type GetTokenListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*GetTokenListResp_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetTokenListResp) Reset() {
	*x = GetTokenListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenlist_v1_tokenlsit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenListResp) ProtoMessage() {}

func (x *GetTokenListResp) ProtoReflect() protoreflect.Message {
	mi := &file_tokenlist_v1_tokenlsit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenListResp.ProtoReflect.Descriptor instead.
func (*GetTokenListResp) Descriptor() ([]byte, []int) {
	return file_tokenlist_v1_tokenlsit_proto_rawDescGZIP(), []int{1}
}

func (x *GetTokenListResp) GetData() []*GetTokenListResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateTokenListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateTokenListReq) Reset() {
	*x = CreateTokenListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenlist_v1_tokenlsit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTokenListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenListReq) ProtoMessage() {}

func (x *CreateTokenListReq) ProtoReflect() protoreflect.Message {
	mi := &file_tokenlist_v1_tokenlsit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenListReq.ProtoReflect.Descriptor instead.
func (*CreateTokenListReq) Descriptor() ([]byte, []int) {
	return file_tokenlist_v1_tokenlsit_proto_rawDescGZIP(), []int{2}
}

type CreateTokenListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateTokenListResp) Reset() {
	*x = CreateTokenListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenlist_v1_tokenlsit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTokenListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenListResp) ProtoMessage() {}

func (x *CreateTokenListResp) ProtoReflect() protoreflect.Message {
	mi := &file_tokenlist_v1_tokenlsit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenListResp.ProtoReflect.Descriptor instead.
func (*CreateTokenListResp) Descriptor() ([]byte, []int) {
	return file_tokenlist_v1_tokenlsit_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTokenListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PriceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoinNames     string `protobuf:"bytes,1,opt,name=coin_names,json=coinNames,proto3" json:"coin_names,omitempty"`
	CoinAddresses string `protobuf:"bytes,2,opt,name=coin_addresses,json=coinAddresses,proto3" json:"coin_addresses,omitempty"`
	Currency      string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *PriceReq) Reset() {
	*x = PriceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenlist_v1_tokenlsit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceReq) ProtoMessage() {}

func (x *PriceReq) ProtoReflect() protoreflect.Message {
	mi := &file_tokenlist_v1_tokenlsit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceReq.ProtoReflect.Descriptor instead.
func (*PriceReq) Descriptor() ([]byte, []int) {
	return file_tokenlist_v1_tokenlsit_proto_rawDescGZIP(), []int{4}
}

func (x *PriceReq) GetCoinNames() string {
	if x != nil {
		return x.CoinNames
	}
	return ""
}

func (x *PriceReq) GetCoinAddresses() string {
	if x != nil {
		return x.CoinAddresses
	}
	return ""
}

func (x *PriceReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type PriceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PriceResp) Reset() {
	*x = PriceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenlist_v1_tokenlsit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceResp) ProtoMessage() {}

func (x *PriceResp) ProtoReflect() protoreflect.Message {
	mi := &file_tokenlist_v1_tokenlsit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceResp.ProtoReflect.Descriptor instead.
func (*PriceResp) Descriptor() ([]byte, []int) {
	return file_tokenlist_v1_tokenlsit_proto_rawDescGZIP(), []int{5}
}

func (x *PriceResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetTokenListResp_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId  uint32 `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address  string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Decimals uint32 `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Symbol   string `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LogoURI  string `protobuf:"bytes,6,opt,name=logoURI,proto3" json:"logoURI,omitempty"`
}

func (x *GetTokenListResp_Data) Reset() {
	*x = GetTokenListResp_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenlist_v1_tokenlsit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenListResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenListResp_Data) ProtoMessage() {}

func (x *GetTokenListResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_tokenlist_v1_tokenlsit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenListResp_Data.ProtoReflect.Descriptor instead.
func (*GetTokenListResp_Data) Descriptor() ([]byte, []int) {
	return file_tokenlist_v1_tokenlsit_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetTokenListResp_Data) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetTokenListResp_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTokenListResp_Data) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetTokenListResp_Data) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *GetTokenListResp_Data) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTokenListResp_Data) GetLogoURI() string {
	if x != nil {
		return x.LogoURI
	}
	return ""
}

var File_tokenlist_v1_tokenlsit_proto protoreflect.FileDescriptor

var file_tokenlist_v1_tokenlsit_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x73, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x61, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x22, 0xee, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x9c, 0x01, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65,
	0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65,
	0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x6f, 0x55, 0x52, 0x49, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6c, 0x6f, 0x67, 0x6f, 0x55, 0x52, 0x49, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x2f,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x6c, 0x0a, 0x08, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x6f, 0x69, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x6f, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f,
	0x69, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x69, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x1f, 0x0a,
	0x09, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xcc,
	0x02, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x73, 0x69, 0x74, 0x12, 0x5d, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x75, 0x0a, 0x0f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x15, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0f, 0x22, 0x0a, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x3a,
	0x01, 0x2a, 0x12, 0x69, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0c, 0x12, 0x0a, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x34, 0x0a,
	0x10, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76,
	0x31, 0x50, 0x01, 0x5a, 0x1e, 0x6e, 0x6f, 0x64, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tokenlist_v1_tokenlsit_proto_rawDescOnce sync.Once
	file_tokenlist_v1_tokenlsit_proto_rawDescData = file_tokenlist_v1_tokenlsit_proto_rawDesc
)

func file_tokenlist_v1_tokenlsit_proto_rawDescGZIP() []byte {
	file_tokenlist_v1_tokenlsit_proto_rawDescOnce.Do(func() {
		file_tokenlist_v1_tokenlsit_proto_rawDescData = protoimpl.X.CompressGZIP(file_tokenlist_v1_tokenlsit_proto_rawDescData)
	})
	return file_tokenlist_v1_tokenlsit_proto_rawDescData
}

var file_tokenlist_v1_tokenlsit_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tokenlist_v1_tokenlsit_proto_goTypes = []interface{}{
	(*GetTokenListReq)(nil),       // 0: api.tokenlist.v1.GetTokenListReq
	(*GetTokenListResp)(nil),      // 1: api.tokenlist.v1.GetTokenListResp
	(*CreateTokenListReq)(nil),    // 2: api.tokenlist.v1.CreateTokenListReq
	(*CreateTokenListResp)(nil),   // 3: api.tokenlist.v1.CreateTokenListResp
	(*PriceReq)(nil),              // 4: api.tokenlist.v1.PriceReq
	(*PriceResp)(nil),             // 5: api.tokenlist.v1.PriceResp
	(*GetTokenListResp_Data)(nil), // 6: api.tokenlist.v1.GetTokenListResp.Data
}
var file_tokenlist_v1_tokenlsit_proto_depIdxs = []int32{
	6, // 0: api.tokenlist.v1.GetTokenListResp.data:type_name -> api.tokenlist.v1.GetTokenListResp.Data
	4, // 1: api.tokenlist.v1.Tokenlsit.GetPrice:input_type -> api.tokenlist.v1.PriceReq
	2, // 2: api.tokenlist.v1.Tokenlsit.CreateTokenList:input_type -> api.tokenlist.v1.CreateTokenListReq
	0, // 3: api.tokenlist.v1.Tokenlsit.GetTokenList:input_type -> api.tokenlist.v1.GetTokenListReq
	5, // 4: api.tokenlist.v1.Tokenlsit.GetPrice:output_type -> api.tokenlist.v1.PriceResp
	3, // 5: api.tokenlist.v1.Tokenlsit.CreateTokenList:output_type -> api.tokenlist.v1.CreateTokenListResp
	1, // 6: api.tokenlist.v1.Tokenlsit.GetTokenList:output_type -> api.tokenlist.v1.GetTokenListResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tokenlist_v1_tokenlsit_proto_init() }
func file_tokenlist_v1_tokenlsit_proto_init() {
	if File_tokenlist_v1_tokenlsit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tokenlist_v1_tokenlsit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenlist_v1_tokenlsit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenlist_v1_tokenlsit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTokenListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenlist_v1_tokenlsit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTokenListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenlist_v1_tokenlsit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenlist_v1_tokenlsit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenlist_v1_tokenlsit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenListResp_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tokenlist_v1_tokenlsit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tokenlist_v1_tokenlsit_proto_goTypes,
		DependencyIndexes: file_tokenlist_v1_tokenlsit_proto_depIdxs,
		MessageInfos:      file_tokenlist_v1_tokenlsit_proto_msgTypes,
	}.Build()
	File_tokenlist_v1_tokenlsit_proto = out.File
	file_tokenlist_v1_tokenlsit_proto_rawDesc = nil
	file_tokenlist_v1_tokenlsit_proto_goTypes = nil
	file_tokenlist_v1_tokenlsit_proto_depIdxs = nil
}
