// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: api/tokenlist/v1/tokenlist.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTokenListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain string `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
}

func (x *GetTokenListReq) Reset() {
	*x = GetTokenListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenListReq) ProtoMessage() {}

func (x *GetTokenListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenListReq.ProtoReflect.Descriptor instead.
func (*GetTokenListReq) Descriptor() ([]byte, []int) {
	return file_api_tokenlist_v1_tokenlist_proto_rawDescGZIP(), []int{0}
}

func (x *GetTokenListReq) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type GetTokenListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*GetTokenListResp_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetTokenListResp) Reset() {
	*x = GetTokenListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenListResp) ProtoMessage() {}

func (x *GetTokenListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenListResp.ProtoReflect.Descriptor instead.
func (*GetTokenListResp) Descriptor() ([]byte, []int) {
	return file_api_tokenlist_v1_tokenlist_proto_rawDescGZIP(), []int{1}
}

func (x *GetTokenListResp) GetData() []*GetTokenListResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type PriceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoinNames     string `protobuf:"bytes,1,opt,name=coin_names,json=coinNames,proto3" json:"coin_names,omitempty"`
	CoinAddresses string `protobuf:"bytes,2,opt,name=coin_addresses,json=coinAddresses,proto3" json:"coin_addresses,omitempty"`
	Currency      string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *PriceReq) Reset() {
	*x = PriceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceReq) ProtoMessage() {}

func (x *PriceReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceReq.ProtoReflect.Descriptor instead.
func (*PriceReq) Descriptor() ([]byte, []int) {
	return file_api_tokenlist_v1_tokenlist_proto_rawDescGZIP(), []int{2}
}

func (x *PriceReq) GetCoinNames() string {
	if x != nil {
		return x.CoinNames
	}
	return ""
}

func (x *PriceReq) GetCoinAddresses() string {
	if x != nil {
		return x.CoinAddresses
	}
	return ""
}

func (x *PriceReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type PriceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PriceResp) Reset() {
	*x = PriceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceResp) ProtoMessage() {}

func (x *PriceResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceResp.ProtoReflect.Descriptor instead.
func (*PriceResp) Descriptor() ([]byte, []int) {
	return file_api_tokenlist_v1_tokenlist_proto_rawDescGZIP(), []int{3}
}

func (x *PriceResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetTokenInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*GetTokenInfoReq_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetTokenInfoReq) Reset() {
	*x = GetTokenInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenInfoReq) ProtoMessage() {}

func (x *GetTokenInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenInfoReq.ProtoReflect.Descriptor instead.
func (*GetTokenInfoReq) Descriptor() ([]byte, []int) {
	return file_api_tokenlist_v1_tokenlist_proto_rawDescGZIP(), []int{4}
}

func (x *GetTokenInfoReq) GetData() []*GetTokenInfoReq_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetTokenInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*GetTokenInfoResp_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetTokenInfoResp) Reset() {
	*x = GetTokenInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenInfoResp) ProtoMessage() {}

func (x *GetTokenInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenInfoResp.ProtoReflect.Descriptor instead.
func (*GetTokenInfoResp) Descriptor() ([]byte, []int) {
	return file_api_tokenlist_v1_tokenlist_proto_rawDescGZIP(), []int{5}
}

func (x *GetTokenInfoResp) GetData() []*GetTokenInfoResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetTokenListResp_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId  uint32 `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address  string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Decimals uint32 `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Symbol   string `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LogoURI  string `protobuf:"bytes,6,opt,name=logoURI,proto3" json:"logoURI,omitempty"`
}

func (x *GetTokenListResp_Data) Reset() {
	*x = GetTokenListResp_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenListResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenListResp_Data) ProtoMessage() {}

func (x *GetTokenListResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenListResp_Data.ProtoReflect.Descriptor instead.
func (*GetTokenListResp_Data) Descriptor() ([]byte, []int) {
	return file_api_tokenlist_v1_tokenlist_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetTokenListResp_Data) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetTokenListResp_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTokenListResp_Data) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetTokenListResp_Data) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *GetTokenListResp_Data) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTokenListResp_Data) GetLogoURI() string {
	if x != nil {
		return x.LogoURI
	}
	return ""
}

type GetTokenInfoReq_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain   string `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetTokenInfoReq_Data) Reset() {
	*x = GetTokenInfoReq_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenInfoReq_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenInfoReq_Data) ProtoMessage() {}

func (x *GetTokenInfoReq_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenInfoReq_Data.ProtoReflect.Descriptor instead.
func (*GetTokenInfoReq_Data) Descriptor() ([]byte, []int) {
	return file_api_tokenlist_v1_tokenlist_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetTokenInfoReq_Data) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *GetTokenInfoReq_Data) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetTokenInfoResp_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain    string `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address  string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Decimals uint32 `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Symbol   string `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LogoURI  string `protobuf:"bytes,6,opt,name=logoURI,proto3" json:"logoURI,omitempty"`
}

func (x *GetTokenInfoResp_Data) Reset() {
	*x = GetTokenInfoResp_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenInfoResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenInfoResp_Data) ProtoMessage() {}

func (x *GetTokenInfoResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenlist_v1_tokenlist_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenInfoResp_Data.ProtoReflect.Descriptor instead.
func (*GetTokenInfoResp_Data) Descriptor() ([]byte, []int) {
	return file_api_tokenlist_v1_tokenlist_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetTokenInfoResp_Data) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *GetTokenInfoResp_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTokenInfoResp_Data) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetTokenInfoResp_Data) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *GetTokenInfoResp_Data) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTokenInfoResp_Data) GetLogoURI() string {
	if x != nil {
		return x.LogoURI
	}
	return ""
}

var File_api_tokenlist_v1_tokenlist_proto protoreflect.FileDescriptor

var file_api_tokenlist_v1_tokenlist_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2f,
	0x76, 0x31, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x76, 0x31, 0x22, 0x27, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x22, 0xee, 0x01,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x3b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0x9c, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x6f, 0x55, 0x52, 0x49, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x6f, 0x55, 0x52, 0x49, 0x22, 0x6c,
	0x0a, 0x08, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f,
	0x69, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6f, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x69,
	0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x6f, 0x69, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x1f, 0x0a, 0x09,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x85, 0x01,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x12, 0x3a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x36, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xea, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x98, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x6f,
	0x55, 0x52, 0x49, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x6f, 0x55,
	0x52, 0x49, 0x32, 0xfe, 0x01, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74,
	0x12, 0x43, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x55, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x55, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a,
	0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x4a, 0x0a, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x2e, 0x62, 0x69, 0x78, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6c, 0x69,
	0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_tokenlist_v1_tokenlist_proto_rawDescOnce sync.Once
	file_api_tokenlist_v1_tokenlist_proto_rawDescData = file_api_tokenlist_v1_tokenlist_proto_rawDesc
)

func file_api_tokenlist_v1_tokenlist_proto_rawDescGZIP() []byte {
	file_api_tokenlist_v1_tokenlist_proto_rawDescOnce.Do(func() {
		file_api_tokenlist_v1_tokenlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_tokenlist_v1_tokenlist_proto_rawDescData)
	})
	return file_api_tokenlist_v1_tokenlist_proto_rawDescData
}

var file_api_tokenlist_v1_tokenlist_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_tokenlist_v1_tokenlist_proto_goTypes = []interface{}{
	(*GetTokenListReq)(nil),       // 0: api.tokenlist.v1.GetTokenListReq
	(*GetTokenListResp)(nil),      // 1: api.tokenlist.v1.GetTokenListResp
	(*PriceReq)(nil),              // 2: api.tokenlist.v1.PriceReq
	(*PriceResp)(nil),             // 3: api.tokenlist.v1.PriceResp
	(*GetTokenInfoReq)(nil),       // 4: api.tokenlist.v1.GetTokenInfoReq
	(*GetTokenInfoResp)(nil),      // 5: api.tokenlist.v1.GetTokenInfoResp
	(*GetTokenListResp_Data)(nil), // 6: api.tokenlist.v1.GetTokenListResp.Data
	(*GetTokenInfoReq_Data)(nil),  // 7: api.tokenlist.v1.GetTokenInfoReq.Data
	(*GetTokenInfoResp_Data)(nil), // 8: api.tokenlist.v1.GetTokenInfoResp.Data
}
var file_api_tokenlist_v1_tokenlist_proto_depIdxs = []int32{
	6, // 0: api.tokenlist.v1.GetTokenListResp.data:type_name -> api.tokenlist.v1.GetTokenListResp.Data
	7, // 1: api.tokenlist.v1.GetTokenInfoReq.data:type_name -> api.tokenlist.v1.GetTokenInfoReq.Data
	8, // 2: api.tokenlist.v1.GetTokenInfoResp.data:type_name -> api.tokenlist.v1.GetTokenInfoResp.Data
	2, // 3: api.tokenlist.v1.Tokenlist.GetPrice:input_type -> api.tokenlist.v1.PriceReq
	0, // 4: api.tokenlist.v1.Tokenlist.GetTokenList:input_type -> api.tokenlist.v1.GetTokenListReq
	4, // 5: api.tokenlist.v1.Tokenlist.GetTokenInfo:input_type -> api.tokenlist.v1.GetTokenInfoReq
	3, // 6: api.tokenlist.v1.Tokenlist.GetPrice:output_type -> api.tokenlist.v1.PriceResp
	1, // 7: api.tokenlist.v1.Tokenlist.GetTokenList:output_type -> api.tokenlist.v1.GetTokenListResp
	5, // 8: api.tokenlist.v1.Tokenlist.GetTokenInfo:output_type -> api.tokenlist.v1.GetTokenInfoResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_tokenlist_v1_tokenlist_proto_init() }
func file_api_tokenlist_v1_tokenlist_proto_init() {
	if File_api_tokenlist_v1_tokenlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_tokenlist_v1_tokenlist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tokenlist_v1_tokenlist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tokenlist_v1_tokenlist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tokenlist_v1_tokenlist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tokenlist_v1_tokenlist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tokenlist_v1_tokenlist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tokenlist_v1_tokenlist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenListResp_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tokenlist_v1_tokenlist_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenInfoReq_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tokenlist_v1_tokenlist_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenInfoResp_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_tokenlist_v1_tokenlist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tokenlist_v1_tokenlist_proto_goTypes,
		DependencyIndexes: file_api_tokenlist_v1_tokenlist_proto_depIdxs,
		MessageInfos:      file_api_tokenlist_v1_tokenlist_proto_msgTypes,
	}.Build()
	File_api_tokenlist_v1_tokenlist_proto = out.File
	file_api_tokenlist_v1_tokenlist_proto_rawDesc = nil
	file_api_tokenlist_v1_tokenlist_proto_goTypes = nil
	file_api_tokenlist_v1_tokenlist_proto_depIdxs = nil
}
