// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.bixin.com/mili/node-proxy/internal/biz"
	"gitlab.bixin.com/mili/node-proxy/internal/conf"
	"gitlab.bixin.com/mili/node-proxy/internal/data"
)

// Injectors from wire.go:

// initTokenListcase init kratos application tokenlistcase.
func initTokenListcase(confData *conf.Data, tokenList *conf.TokenList, logger log.Logger) (*biz.TokenListUsecase, func(), error) {
	db := data.NewDB(confData, logger)
	client := data.NewRedis(confData)
	tokenListRepo := data.NewTokenListRepo(tokenList, db, client, logger)
	tokenListUsecase := biz.NewTokenListUsecase(tokenListRepo, logger)
	return tokenListUsecase, func() {
	}, nil
}
