// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.bixin.com/mili/node-proxy/internal/biz"
	"gitlab.bixin.com/mili/node-proxy/internal/conf"
	"gitlab.bixin.com/mili/node-proxy/internal/data"
)

// Injectors from wire.go:

// initNFTcase init kratos application tokenlistcase.
func initNFTcase(confData *conf.Data, tokenList *conf.NFTList, logger log.Logger) (*biz.NFTUsecase, func(), error) {
	db := data.NewDB(confData, logger)
	nftRepo := data.NewNFTRepo(db, logger, tokenList)
	nftUsecase := biz.NewNFTUsecase(nftRepo, logger)
	return nftUsecase, func() {
	}, nil
}
