// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: api/nft-marketplace/v1/nft_api.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NFTApiClient is the client API for NFTApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NFTApiClient interface {
	Info(ctx context.Context, in *InfoApiReq, opts ...grpc.CallOption) (*InfoApiResp, error)
}

type nFTApiClient struct {
	cc grpc.ClientConnInterface
}

func NewNFTApiClient(cc grpc.ClientConnInterface) NFTApiClient {
	return &nFTApiClient{cc}
}

func (c *nFTApiClient) Info(ctx context.Context, in *InfoApiReq, opts ...grpc.CallOption) (*InfoApiResp, error) {
	out := new(InfoApiResp)
	err := c.cc.Invoke(ctx, "/nft.v1.NFTApi/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NFTApiServer is the server API for NFTApi service.
// All implementations must embed UnimplementedNFTApiServer
// for forward compatibility
type NFTApiServer interface {
	Info(context.Context, *InfoApiReq) (*InfoApiResp, error)
	mustEmbedUnimplementedNFTApiServer()
}

// UnimplementedNFTApiServer must be embedded to have forward compatible implementations.
type UnimplementedNFTApiServer struct {
}

func (UnimplementedNFTApiServer) Info(context.Context, *InfoApiReq) (*InfoApiResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedNFTApiServer) mustEmbedUnimplementedNFTApiServer() {}

// UnsafeNFTApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NFTApiServer will
// result in compilation errors.
type UnsafeNFTApiServer interface {
	mustEmbedUnimplementedNFTApiServer()
}

func RegisterNFTApiServer(s grpc.ServiceRegistrar, srv NFTApiServer) {
	s.RegisterService(&NFTApi_ServiceDesc, srv)
}

func _NFTApi_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFTApiServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nft.v1.NFTApi/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFTApiServer).Info(ctx, req.(*InfoApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

// NFTApi_ServiceDesc is the grpc.ServiceDesc for NFTApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NFTApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nft.v1.NFTApi",
	HandlerType: (*NFTApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _NFTApi_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/nft-marketplace/v1/nft_api.proto",
}
