// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: api/nft-marketplace/v2/collection_api.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoApiReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 合约地址
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// 链 1-ethereum
	Chain string `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
}

func (x *InfoApiReq) Reset() {
	*x = InfoApiReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_nft_marketplace_v2_collection_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoApiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoApiReq) ProtoMessage() {}

func (x *InfoApiReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_nft_marketplace_v2_collection_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoApiReq.ProtoReflect.Descriptor instead.
func (*InfoApiReq) Descriptor() ([]byte, []int) {
	return file_api_nft_marketplace_v2_collection_api_proto_rawDescGZIP(), []int{0}
}

func (x *InfoApiReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *InfoApiReq) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type InfoApiResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool              `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrMsg string            `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Data   *InfoApiResp_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *InfoApiResp) Reset() {
	*x = InfoApiResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_nft_marketplace_v2_collection_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoApiResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoApiResp) ProtoMessage() {}

func (x *InfoApiResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_nft_marketplace_v2_collection_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoApiResp.ProtoReflect.Descriptor instead.
func (*InfoApiResp) Descriptor() ([]byte, []int) {
	return file_api_nft_marketplace_v2_collection_api_proto_rawDescGZIP(), []int{1}
}

func (x *InfoApiResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *InfoApiResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *InfoApiResp) GetData() *InfoApiResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type InfoApiResp_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 合集名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 合集合约地址
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// 合集描述
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// 合集logo
	Logo string `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	// 合集banner图
	Banner string `protobuf:"bytes,5,opt,name=banner,proto3" json:"banner,omitempty"`
	// 合集类型
	ErcType string `protobuf:"bytes,6,opt,name=ercType,proto3" json:"ercType,omitempty"`
	// 链
	Chain string `protobuf:"bytes,7,opt,name=chain,proto3" json:"chain,omitempty"`
}

func (x *InfoApiResp_Data) Reset() {
	*x = InfoApiResp_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_nft_marketplace_v2_collection_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoApiResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoApiResp_Data) ProtoMessage() {}

func (x *InfoApiResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_nft_marketplace_v2_collection_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoApiResp_Data.ProtoReflect.Descriptor instead.
func (*InfoApiResp_Data) Descriptor() ([]byte, []int) {
	return file_api_nft_marketplace_v2_collection_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *InfoApiResp_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoApiResp_Data) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *InfoApiResp_Data) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InfoApiResp_Data) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *InfoApiResp_Data) GetBanner() string {
	if x != nil {
		return x.Banner
	}
	return ""
}

func (x *InfoApiResp_Data) GetErcType() string {
	if x != nil {
		return x.ErcType
	}
	return ""
}

func (x *InfoApiResp_Data) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

var File_api_nft_marketplace_v2_collection_api_proto protoreflect.FileDescriptor

var file_api_nft_marketplace_v2_collection_api_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x66, 0x74, 0x2d, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x2f, 0x76, 0x32, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x3c, 0x0a, 0x0a,
	0x49, 0x6e, 0x66, 0x6f, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x22, 0x9f, 0x02, 0x0a, 0x0b, 0x49,
	0x6e, 0x66, 0x6f, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72,
	0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d,
	0x73, 0x67, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xb2, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6c, 0x6f, 0x67, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x72, 0x63, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x72, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x32, 0x50, 0x0a, 0x0d,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x70, 0x69, 0x12, 0x3f, 0x0a,
	0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71,
	0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x59,
	0x0a, 0x1c, 0x64, 0x65, 0x76, 0x2e, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x42, 0x11,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x56,
	0x31, 0x50, 0x01, 0x5a, 0x24, 0x6e, 0x66, 0x74, 0x2d, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_nft_marketplace_v2_collection_api_proto_rawDescOnce sync.Once
	file_api_nft_marketplace_v2_collection_api_proto_rawDescData = file_api_nft_marketplace_v2_collection_api_proto_rawDesc
)

func file_api_nft_marketplace_v2_collection_api_proto_rawDescGZIP() []byte {
	file_api_nft_marketplace_v2_collection_api_proto_rawDescOnce.Do(func() {
		file_api_nft_marketplace_v2_collection_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_nft_marketplace_v2_collection_api_proto_rawDescData)
	})
	return file_api_nft_marketplace_v2_collection_api_proto_rawDescData
}

var file_api_nft_marketplace_v2_collection_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_nft_marketplace_v2_collection_api_proto_goTypes = []interface{}{
	(*InfoApiReq)(nil),       // 0: collection.v1.InfoApiReq
	(*InfoApiResp)(nil),      // 1: collection.v1.InfoApiResp
	(*InfoApiResp_Data)(nil), // 2: collection.v1.InfoApiResp.Data
}
var file_api_nft_marketplace_v2_collection_api_proto_depIdxs = []int32{
	2, // 0: collection.v1.InfoApiResp.data:type_name -> collection.v1.InfoApiResp.Data
	0, // 1: collection.v1.CollectionApi.Info:input_type -> collection.v1.InfoApiReq
	1, // 2: collection.v1.CollectionApi.Info:output_type -> collection.v1.InfoApiResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_nft_marketplace_v2_collection_api_proto_init() }
func file_api_nft_marketplace_v2_collection_api_proto_init() {
	if File_api_nft_marketplace_v2_collection_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_nft_marketplace_v2_collection_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoApiReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_nft_marketplace_v2_collection_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoApiResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_nft_marketplace_v2_collection_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoApiResp_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_nft_marketplace_v2_collection_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_nft_marketplace_v2_collection_api_proto_goTypes,
		DependencyIndexes: file_api_nft_marketplace_v2_collection_api_proto_depIdxs,
		MessageInfos:      file_api_nft_marketplace_v2_collection_api_proto_msgTypes,
	}.Build()
	File_api_nft_marketplace_v2_collection_api_proto = out.File
	file_api_nft_marketplace_v2_collection_api_proto_rawDesc = nil
	file_api_nft_marketplace_v2_collection_api_proto_goTypes = nil
	file_api_nft_marketplace_v2_collection_api_proto_depIdxs = nil
}
