// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: api/nft/v1/nft.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NftClient is the client API for Nft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NftClient interface {
	GetNftInfo(ctx context.Context, in *GetNftInfoRequest, opts ...grpc.CallOption) (*GetNftReply, error)
	NetNftCollectionInfo(ctx context.Context, in *GetNftCollectionInfoReq, opts ...grpc.CallOption) (*GetNftCollectionInfoReply, error)
}

type nftClient struct {
	cc grpc.ClientConnInterface
}

func NewNftClient(cc grpc.ClientConnInterface) NftClient {
	return &nftClient{cc}
}

func (c *nftClient) GetNftInfo(ctx context.Context, in *GetNftInfoRequest, opts ...grpc.CallOption) (*GetNftReply, error) {
	out := new(GetNftReply)
	err := c.cc.Invoke(ctx, "/api.nft.v1.Nft/GetNftInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) NetNftCollectionInfo(ctx context.Context, in *GetNftCollectionInfoReq, opts ...grpc.CallOption) (*GetNftCollectionInfoReply, error) {
	out := new(GetNftCollectionInfoReply)
	err := c.cc.Invoke(ctx, "/api.nft.v1.Nft/NetNftCollectionInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NftServer is the server API for Nft service.
// All implementations must embed UnimplementedNftServer
// for forward compatibility
type NftServer interface {
	GetNftInfo(context.Context, *GetNftInfoRequest) (*GetNftReply, error)
	NetNftCollectionInfo(context.Context, *GetNftCollectionInfoReq) (*GetNftCollectionInfoReply, error)
	mustEmbedUnimplementedNftServer()
}

// UnimplementedNftServer must be embedded to have forward compatible implementations.
type UnimplementedNftServer struct {
}

func (UnimplementedNftServer) GetNftInfo(context.Context, *GetNftInfoRequest) (*GetNftReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNftInfo not implemented")
}
func (UnimplementedNftServer) NetNftCollectionInfo(context.Context, *GetNftCollectionInfoReq) (*GetNftCollectionInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetNftCollectionInfo not implemented")
}
func (UnimplementedNftServer) mustEmbedUnimplementedNftServer() {}

// UnsafeNftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NftServer will
// result in compilation errors.
type UnsafeNftServer interface {
	mustEmbedUnimplementedNftServer()
}

func RegisterNftServer(s grpc.ServiceRegistrar, srv NftServer) {
	s.RegisterService(&Nft_ServiceDesc, srv)
}

func _Nft_GetNftInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNftInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).GetNftInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.nft.v1.Nft/GetNftInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).GetNftInfo(ctx, req.(*GetNftInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_NetNftCollectionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNftCollectionInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).NetNftCollectionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.nft.v1.Nft/NetNftCollectionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).NetNftCollectionInfo(ctx, req.(*GetNftCollectionInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Nft_ServiceDesc is the grpc.ServiceDesc for Nft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.nft.v1.Nft",
	HandlerType: (*NftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNftInfo",
			Handler:    _Nft_GetNftInfo_Handler,
		},
		{
			MethodName: "NetNftCollectionInfo",
			Handler:    _Nft_NetNftCollectionInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/nft/v1/nft.proto",
}
