// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"node-proxy/internal/biz"
	"node-proxy/internal/conf"
	"node-proxy/internal/data"
	"node-proxy/internal/server"
	"node-proxy/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, tokenList *conf.TokenList, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	tokenListRepo := data.NewTokenListRepo(tokenList, db, client, logger)
	tokenListUsecase := biz.NewTokenListUsecase(tokenListRepo, logger)
	tokenlsitService := service.NewTokenlsitService(tokenListUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, tokenlsitService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, tokenlsitService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
