server:
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    driver: postgres
    source: host=127.0.0.1 user=haobtc password=haobtc.asd dbname=mpcwallet port=5432 sslmode=disable TimeZone=Asia/Shanghai
  redis:
    addr: 127.0.0.1:6379
    db: 9
    read_timeout: 0.2s
    write_timeout: 0.2s
tokenList:
  logoPrefix: https://obstatic.243096.com/download/token/
  coingecko:
    baseURL: https://api.coingecko.com/api/v3
  coinmarketcap:
    baseURL: https://pro-api.coinmarketcap.com/v1
    key: 4a77c975-64ff-4c2e-8f70-b195bfb07be5
  qiniu:
    accessKey: EaebIDbEDcyKefx72vRpG3-JDa5Hd9YInXYRiTst
    secretKey: OYNl6ub3YfNI2hVOJ-h6KqRFuwPpUeL4MmVDU9Ia
    bucket: obstatic
    keyPrefix: download/token/