server:
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    driver: postgres
    source: host=127.0.0.1 user=haobtc password=haobtc.asd dbname=mpcwallet port=5432 sslmode=disable TimeZone=Asia/Shanghai
  redis:
    addr: 127.0.0.1:6379
    db: 9
    read_timeout: 0.2s
    write_timeout: 0.2s
tokenList:
  logoPrefix: https://obstatic.243096.com/download/tokentest/
  awsLogoPrefix: https://obstaticaws.243096.com/download/tokentest/
  coingecko:
    baseURL: https://api.coingecko.com/api/v3
  coinmarketcap:
    baseURL: https://pro-api.coinmarketcap.com/v1
    key:
      - 411e33ba-1371-4068-874d-6128776c8dd3
      - 4a77c975-64ff-4c2e-8f70-b195bfb07be5
      - 954fb4aa-a1ab-42e2-8476-685832faeda4
      - 4a77c975-64ff-4c2e-8f70-b195bfb07be5
      - 9f36b36d-97aa-48f5-9a20-a41bf6888396
      - dd8eb4f4-922b-43a1-bd2c-671925ca3ed3
      - 03eca6eb-77f9-4ce7-b265-ee408b424d45
  qiniu:
    accessKey: EaebIDbEDcyKefx72vRpG3-JDa5Hd9YInXYRiTst
    secretKey: OYNl6ub3YfNI2hVOJ-h6KqRFuwPpUeL4MmVDU9Ia
    bucket:
      - obstatic
      - obstatic-sgaws
    keyPrefix: download/tokentest/
  aws:
    - accessKey: accessKey
      secretKey: secretKey
      bucket: bixin-obstatic
      region: region
      keyPrefix: /download/tokentest/
      distributionId: distributionId
  chains:
    - ETH
    - HECO
    - OEC
    - BSC
    - Polygon
    - Fantom
    - Avalanche
    - Cronos
    - Arbitrum
    - Klaytn
    - Aurora
    - Optimism
    - Oasis
    - TRX
    - xDai
    - ETC
    - Solana
    - Aptos
    - Nervos
    - STC
    - SmartBCH
    - Osmosis

nftList:
  ipfs: https://cloudflare-ipfs.com/ipfs/

platform:
  - chain: Cronos
    type: EVM
    rpcURL:
      - https://evm.cronos.org
      - https://rpc.artemisone.org/cronos
      - https://rpc.vvs.finance/
  - chain: BSC
    type: EVM
    rpcURL:
      - https://rpc.ankr.com/bsc
      - https://bsc-dataseed.binance.org/
      - https://bsc-dataseed1.binance.org
      - https://bsc-dataseed2.binance.org
      - https://bsc-dataseed3.binance.org
      - https://bsc-dataseed4.binance.org
      - https://bsc-dataseed1.ninicoin.io
      - https://bsc-dataseed2.ninicoin.io
      - https://bsc-dataseed3.ninicoin.io
      - https://bsc-dataseed4.ninicoin.io
      - https://bsc-dataseed1.defibit.io
      - https://bsc-dataseed2.defibit.io
      - https://bsc-dataseed3.defibit.io
      - https://bsc-dataseed4.defibit.io
      - https://binance.ankr.com
      - https://rpc.onekey.so/bsc
  - chain: BTC
    type: BTC
    rpcURL:
      - https://api.blockcypher.com/v1/btc/main
      - https://chain.so
      - https://blockstream.info
  - chain: Cronos
    type: EVM
    rpcURL:
      - https://evm.cronos.org
      - https://rpc.artemisone.org/cronos
      - https://rpc.vvs.finance/
  - chain: ETH
    type: EVM
    rpcURL:
      - https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
      - https://geth.mytokenpocket.vip
      - https://rpc.onekey.so/eth
      - https://eth626892d.jccdex.cn
      - https://web3.mytokenpocket.vip
      - https://rpc.flashbots.net
      - https://web3os.tokenpocket.pro
      - https://rpc.ankr.com/eth
  - chain: Fantom
    type: EVM
    rpcURL:
      - https://rpc.ftm.tools/
      - https://rpcapi.fantom.network
      - https://rpc.ankr.com/fantom
  - chain: HECO
    type: EVM
    rpcURL:
      - https://http-mainnet.hecochain.com/
      - https://http-mainnet-node.defibox.com
  - chain: Klaytn
    type: EVM
    rpcURL:
      - https://public-node-api.klaytnapi.com/v1/cypress
      - https://klaytn01.fandom.finance/
      - https://klaytn02.fandom.finance/
      - https://klaytn03.fandom.finance/
      - https://klaytn04.fandom.finance/
      - https://klaytn05.fandom.finance/
  - chain: OEC
    type: EVM
    rpcURL:
      - https://exchainrpc.okex.org/
      - https://okchain.mytokenpocket.vip/
  - chain: Avalanche
    type: EVM
    rpcURL:
      - https://exchainrpc.okex.org/
      - https://okchain.mytokenpocket.vip/
  - chain: Optimism
    type: EVM
    rpcURL:
      - https://mainnet.optimism.io
      - https://optimism-mainnet.public.blastapi.io
      - https://optimism-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
  - chain: Polygon
    type: EVM
    rpcURL:
      - https://rpc-mainnet.maticvigil.com/
      - https://polygon-rpc.com
      - https://matic-mainnet.chainstacklabs.com
      - https://rpc-mainnet.matic.quiknode.pro
      - https://matic-mainnet-archive-rpc.bwarelabs.com
      - https://matic.mytokenpocket.vip
      - https://rpc.ankr.com/polygon
  - chain: STC
    type: STC
    rpcURL:
      - https://main-seed.starcoin.org
  - chain: TRX
    type: TVM
    rpcURL:
      - https://api.trongrid.io
      - https://api.tronstack.io
  - chain: Aptos
    type: APTOS
    rpcURL:
      - https://fullnode.mainnet.aptoslabs.com/v1
      - https://aptos-mainnet.pontem.network/v1
      - https://fullnode.mainnet.martianwallet.xyz/v1
  - chain: xDai
    type: EVM
    rpcURL:
      - https://rpc.ankr.com/gnosis
      - https://gnosischain-rpc.gateway.pokt.network
      - https://xdai-rpc.gateway.pokt.network
      - https://gnosis-mainnet.public.blastapi.io
      - https://rpc.gnosischain.com
  - chain: ETC
    type: EVM
    rpcURL:
      - https://etc.mytokenpocket.vip
      - https://etc.etcdesktop.com
      - https://www.ethercluster.com/etc
  - chain: Solana
    type: SOL
    rpcURL:
      - https://api.mainnet-beta.solana.com
      - https://ssc-dao.genesysgo.net
      - https://solana-api.projectserum.com
      - https://rpc.ankr.com/solana
  - chain: Arbitrum
    type: EVM
    rpcURL:
      - https://arb1.arbitrum.io/rpc
      - https://rpc.ankr.com/arbitrum
      - https://arbitrum-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
  - chain: Cosmos
    type: COSMOS
    rpcURL:
      - https://cosmos-mainnet-rpc.allthatnode.com:1317
      - https://api.cosmos.network
      - https://us-atom-restapi.binancechain.io
  - chain: Casper
    type: CSPR
    rpcURL:
      - https://node-clarity-mainnet.make.services/rpc
  - chain: SmartBCH
    type: EVM
    rpcURL:
      - https://global.uat.cash
      - https://smartbch.greyh.at
  - chain: Osmosis
    type: COSMOS
    rpcURL:
      - https://osmosis-mainnet-rpc.allthatnode.com:1317
      - https://lcd-osmosis.cosmostation.io
      - https://lcd.osmosis.zone

  - chain: AvalancheTEST
    type: EVM
    rpcURL:
      - https://api.avax-test.network/ext/bc/C/rpc
  - chain: BSCTEST
    type: EVM
    rpcURL:
      - https://data-seed-prebsc-1-s1.binance.org:8545
      - https://data-seed-prebsc-1-s2.binance.org:8545
      - https://data-seed-prebsc-1-s3.binance.org:8545
      - https://data-seed-prebsc-2-s1.binance.org:8545
      - https://data-seed-prebsc-2-s2.binance.org:8545
      - https://data-seed-prebsc-2-s3.binance.org:8545
  - chain: BTCTEST
    type: BTC
    rpcURL:
      - https://api.blockcypher.com/v1/btc/test3
  - chain: CronosTEST
    type: EVM
    rpcURL:
      - https://evm-t3.cronos.org/
      - https://cronos-testnet-3.crypto.org:8545
  - chain: ETHTEST
    type: EVM
    rpcURL:
      - https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
  - chain: FantomTEST
    type: EVM
    rpcURL:
      - https://xapi.testnet.fantom.network/lachesis
  - chain: HECOTEST
    type: EVM
    rpcURL:
      - https://http-testnet.hecochain.com/
  - chain: KlaytnTEST
    type: EVM
    rpcURL:
      - https://public-node-api.klaytnapi.com/v1/baobab
      - https://baobab01.fandom.finance
      - https://baobab02.fandom.finance
  - chain: OECTEST
    type: EVM
    rpcURL:
      - https://exchaintestrpc.okex.org
  - chain: OptimismTEST
    type: EVM
    rpcURL:
      - https://kovan.optimism.io
      - https://optimism-kovan.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
  - chain: PolygonTEST
    type: EVM
    rpcURL:
      - https://rpc-mumbai.matic.today
      - https://rpc.ankr.com/polygon_mumbai
      - https://matic-testnet-archive-rpc.bwarelabs.com
      - https://rpc-mumbai.maticvigil.com
      - https://polygontestapi.terminet.io/rpc
      - https://matic-mumbai.chainstacklabs.com
  - chain: TRXTEST
    type: TVM
    rpcURL:
      - https://api.shasta.trongrid.io
  - chain: SuiTEST
    type: SUI
    rpcURL:
      - https://gateway.devnet.sui.io
  - chain: AptosTEST
    type: APTOS
    rpcURL:
      - https://testnet.aptoslabs.com/v1
  - chain: SolanaTEST
    type: SOL
    rpcURL:
      - https://api.testnet.solana.com
  - chain: ArbitrumTEST
    type: EVM
    rpcURL:
      - https://rinkeby.arbitrum.io/rpc
      - https://arbitrum-rinkeby.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
  - chain: CosmosTEST
    type: COSMOS
    rpcURL:
      - https://cosmos-testnet-rpc.allthatnode.com:1317
  - chain: zkSyncTEST
    type: EVM
    rpcURL:
      - https://zksync2-testnet.zksync.dev
  - chain: ScrollL1TEST
    type: EVM
    rpcURL:
      - https://prealpha.scroll.io/l1
  - chain: ScrollL2TEST
    type: EVM
    rpcURL:
      - https://prealpha.scroll.io/l2
  - chain: CasperTEST
    type: CSPR
    rpcURL:
      - https://node-clarity-testnet.make.services/rpc
