// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.bixin.com/mili/node-proxy/internal/biz"
	"gitlab.bixin.com/mili/node-proxy/internal/conf"
	"gitlab.bixin.com/mili/node-proxy/internal/data"
	"gitlab.bixin.com/mili/node-proxy/internal/jobs"
	"gitlab.bixin.com/mili/node-proxy/internal/server"
	"gitlab.bixin.com/mili/node-proxy/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, tokenList *conf.TokenList, arg []*conf.Platform, nftList *conf.NFTList, arg2 *conf.ChainData, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	client := data.NewRedis(confData)
	tokenListRepo := data.NewTokenListRepo(tokenList, db, client, logger)
	tokenListUsecase := biz.NewTokenListUsecase(tokenListRepo, logger)
	tokenlistService := service.NewTokenlistService(tokenListUsecase)
	chainListRepo := data.NewChainListRepo(db, client, logger)
	chainListUsecase := biz.NewChainListUsecase(chainListRepo, logger)
	chainListService := service.NewChainListService(chainListUsecase)
	platformRepo := data.NewPlatformRepo(arg, logger, client)
	platformUseCase := biz.NewPlatformUseCase(platformRepo, logger)
	platformService := service.NewPlatformService(platformUseCase)
	nftRepo := data.NewNFTRepo(db, logger, nftList)
	nftApiClient := data.NewNFTApiClient(nftList)
	collectionApiClient := data.NewCollectionApiClient(nftList)
	nftUsecase := biz.NewNFTUsecase(nftRepo, nftApiClient, collectionApiClient, logger)
	nftService := service.NewNFTService(nftUsecase)
	commRPCRepo := data.NewCommRPCRepo(logger, arg, arg2)
	commRPCUsecase := biz.NewCommRPCUsecase(commRPCRepo, logger)
	commRPCService := service.NewCommRPCService(commRPCUsecase)
	chainListGetNodeUrlJob := jobs.NewChainListGetNodeUrlJob(db, client, logger)
	marketClient := data.NewMarketClient(tokenList)
	topCoinJob := jobs.NewTopCoinJob(db, client, marketClient, logger)
	updateTokenListJob := jobs.NewUpdateTokenListJob(logger)
	cron := jobs.NewJobManager(chainListGetNodeUrlJob, topCoinJob, updateTokenListJob)
	grpcServer := server.NewGRPCServer(confServer, tokenlistService, chainListService, platformService, nftService, commRPCService, cron, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
