// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: api/commRPC/v1/commRPC.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecNodeProxyRPCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Jsonrpc string `protobuf:"bytes,2,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"`
	Method  string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Params  string `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *ExecNodeProxyRPCRequest) Reset() {
	*x = ExecNodeProxyRPCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commRPC_v1_commRPC_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecNodeProxyRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecNodeProxyRPCRequest) ProtoMessage() {}

func (x *ExecNodeProxyRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commRPC_v1_commRPC_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecNodeProxyRPCRequest.ProtoReflect.Descriptor instead.
func (*ExecNodeProxyRPCRequest) Descriptor() ([]byte, []int) {
	return file_api_commRPC_v1_commRPC_proto_rawDescGZIP(), []int{0}
}

func (x *ExecNodeProxyRPCRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExecNodeProxyRPCRequest) GetJsonrpc() string {
	if x != nil {
		return x.Jsonrpc
	}
	return ""
}

func (x *ExecNodeProxyRPCRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ExecNodeProxyRPCRequest) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

type ExecNodeProxyRPCReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	ErrMsg string `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *ExecNodeProxyRPCReply) Reset() {
	*x = ExecNodeProxyRPCReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commRPC_v1_commRPC_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecNodeProxyRPCReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecNodeProxyRPCReply) ProtoMessage() {}

func (x *ExecNodeProxyRPCReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commRPC_v1_commRPC_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecNodeProxyRPCReply.ProtoReflect.Descriptor instead.
func (*ExecNodeProxyRPCReply) Descriptor() ([]byte, []int) {
	return file_api_commRPC_v1_commRPC_proto_rawDescGZIP(), []int{1}
}

func (x *ExecNodeProxyRPCReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ExecNodeProxyRPCReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecNodeProxyRPCReply) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_api_commRPC_v1_commRPC_proto protoreflect.FileDescriptor

var file_api_commRPC_v1_commRPC_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x52, 0x50, 0x43, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x52, 0x50, 0x43, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x52, 0x50, 0x43, 0x2e, 0x76, 0x31, 0x22, 0x73,
	0x0a, 0x17, 0x45, 0x78, 0x65, 0x63, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52,
	0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x73, 0x6f,
	0x6e, 0x72, 0x70, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x73, 0x6f, 0x6e,
	0x72, 0x70, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x22, 0x57, 0x0a, 0x15, 0x45, 0x78, 0x65, 0x63, 0x4e, 0x6f, 0x64, 0x65, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x52, 0x50, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x32, 0x6d, 0x0a, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x52, 0x50, 0x43, 0x12, 0x62, 0x0a, 0x10, 0x45, 0x78, 0x65, 0x63, 0x4e,
	0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x50, 0x43, 0x12, 0x27, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x52, 0x50, 0x43, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x52,
	0x50, 0x43, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72,
	0x6f, 0x78, 0x79, 0x52, 0x50, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x46, 0x0a, 0x0e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x52, 0x50, 0x43, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a,
	0x32, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x62, 0x69, 0x78, 0x69, 0x6e, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6d, 0x69, 0x6c, 0x69, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x52, 0x50, 0x43, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_commRPC_v1_commRPC_proto_rawDescOnce sync.Once
	file_api_commRPC_v1_commRPC_proto_rawDescData = file_api_commRPC_v1_commRPC_proto_rawDesc
)

func file_api_commRPC_v1_commRPC_proto_rawDescGZIP() []byte {
	file_api_commRPC_v1_commRPC_proto_rawDescOnce.Do(func() {
		file_api_commRPC_v1_commRPC_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_commRPC_v1_commRPC_proto_rawDescData)
	})
	return file_api_commRPC_v1_commRPC_proto_rawDescData
}

var file_api_commRPC_v1_commRPC_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_commRPC_v1_commRPC_proto_goTypes = []interface{}{
	(*ExecNodeProxyRPCRequest)(nil), // 0: api.commRPC.v1.ExecNodeProxyRPCRequest
	(*ExecNodeProxyRPCReply)(nil),   // 1: api.commRPC.v1.ExecNodeProxyRPCReply
}
var file_api_commRPC_v1_commRPC_proto_depIdxs = []int32{
	0, // 0: api.commRPC.v1.CommRPC.ExecNodeProxyRPC:input_type -> api.commRPC.v1.ExecNodeProxyRPCRequest
	1, // 1: api.commRPC.v1.CommRPC.ExecNodeProxyRPC:output_type -> api.commRPC.v1.ExecNodeProxyRPCReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_commRPC_v1_commRPC_proto_init() }
func file_api_commRPC_v1_commRPC_proto_init() {
	if File_api_commRPC_v1_commRPC_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_commRPC_v1_commRPC_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecNodeProxyRPCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commRPC_v1_commRPC_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecNodeProxyRPCReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_commRPC_v1_commRPC_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_commRPC_v1_commRPC_proto_goTypes,
		DependencyIndexes: file_api_commRPC_v1_commRPC_proto_depIdxs,
		MessageInfos:      file_api_commRPC_v1_commRPC_proto_msgTypes,
	}.Build()
	File_api_commRPC_v1_commRPC_proto = out.File
	file_api_commRPC_v1_commRPC_proto_rawDesc = nil
	file_api_commRPC_v1_commRPC_proto_goTypes = nil
	file_api_commRPC_v1_commRPC_proto_depIdxs = nil
}
